export enum ErrorCode{
  Email_ALREADY_EXISTS='EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS='USERNAME_ALREADY-EXISTS',
  USER_NOT_FOUND='USER_NOT_FOUND',
  PASSWORD_INCORRECT='PASSWORD_INCORRECT'
}